### ISSUE TITLE
unicode() for Python 3

### ISSUE THREAD

**Issue by cclauss** [IOActive/XDiFF#4]
Would this work?
```python
try:
    unicode        # Python 2
except NameError:
    unicode = str  # Python 3
```
In Python 3 there are two definitions of str() https://docs.python.org/3/library/stdtypes.html#str

The porting best practice is to __use feature detection, not version detection__.  https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection

If this approach does not work, please let me know.

**Comment by farnaboldi** [comment]
Clearly it's a common [approach](https://stackoverflow.com/questions/38697037/how-to-convert-python-2-unicode-function-into-correct-python-3-x-syntax) to this issue. I tried it but it didn't work well with the _errors='ignore'_ parameter. I changed it to use an approach based on your recommendation; this snippet doesn't require the sys library and it does not perform the version detection, and works as expected:
```
try:
	unicode                           # Python 2
except NameError:
	def unicode(value, errors=None):  # Python 3
		return str(value)
```
Thank you for this @cclauss !
